FROM python:3.10.5-slim-bullseye

RUN apt-get update && \
	apt-get install -y

ARG APP_NAME=zenkraft-test
ARG APP_DIR=/usr/bin/$APP_NAME

# Install requirements.
RUN mkdir -p $APP_DIR
COPY requirements.txt $APP_DIR/
WORKDIR $APP_DIR
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy application files.
COPY app $APP_DIR/app
COPY config.py $APP_DIR/config.py
COPY manage.py $APP_DIR/manage.py
COPY VERSION $APP_DIR/VERSION

CMD [ "python3", "manage.py" ]
EXPOSE 8080
