# -*- coding: utf-8 -*-
"""'Externally' adjustable config vars.
"""
from os import environ

# TODO: validation is a good idea.

# Are we in production? False by default.
PRODUCTION = bool(int(environ.get('PRODUCTION', '0')))

# Default HTTPS port by default.
PORT = int(environ['PORT']) if 'PORT' in environ else 443

# Will be used as a default value in FE input form.
TRACKING_NUMBER_DEFAULT_VALUE = environ.get('TRACKING_NUMBER_DEFAULT_VALUE', '')

# Everything for tracking through FedEx.
# Should we use old SOAP endpoints for tracking or new REST?
FEDEX_TRACKING_USE_SOAP = bool(int(environ.get('FEDEX_TRACKING_USE_SOAP', '0')))
# Let's minimize possibility of wrong envs by using different input names for
# dev and prod environment.
if PRODUCTION:
	if FEDEX_TRACKING_USE_SOAP:
		FEDEX_TRACKING_SOAP_PARENT_KEY = environ['FEDEX_TRACKING_SOAP_PARENT_KEY']
		FEDEX_TRACKING_SOAP_PARENT_PASSWORD = environ['FEDEX_TRACKING_SOAP_PARENT_PASSWORD']
		FEDEX_TRACKING_SOAP_USER_KEY = environ['FEDEX_TRACKING_SOAP_USER_KEY']
		FEDEX_TRACKING_SOAP_USER_PASSWORD = environ['FEDEX_TRACKING_SOAP_USER_PASSWORD']
		FEDEX_TRACKING_SOAP_CLIENT_ACCOUNT = environ['FEDEX_TRACKING_SOAP_CLIENT_ACCOUNT']
		FEDEX_TRACKING_SOAP_CLIENT_METER = environ['FEDEX_TRACKING_SOAP_CLIENT_METER']
		FEDEX_TRACKING_SOAP_VERSION_MAJOR = environ['FEDEX_TRACKING_SOAP_VERSION_MAJOR']
		FEDEX_TRACKING_SOAP_VERSION_MIDDLE = environ['FEDEX_TRACKING_SOAP_VERSION_MIDDLE']
		FEDEX_TRACKING_SOAP_VERSION_MINOR = environ['FEDEX_TRACKING_SOAP_VERSION_MINOR']
	else:
		FEDEX_URL = environ['FEDEX_URL']
		FEDEX_TRACKING_API_KEY = environ['FEDEX_TRACKING_API_KEY']
		FEDEX_TRACKING_SECRET_KEY = environ['FEDEX_TRACKING_SECRET_KEY']
else:
	# '_SANDBOX' added for all input names.
	if FEDEX_TRACKING_USE_SOAP:
		FEDEX_TRACKING_SOAP_PARENT_KEY = environ['FEDEX_TRACKING_SOAP_SANDBOX_PARENT_KEY']
		FEDEX_TRACKING_SOAP_PARENT_PASSWORD = environ['FEDEX_TRACKING_SOAP_SANDBOX_PARENT_PASSWORD']
		FEDEX_TRACKING_SOAP_USER_KEY = environ['FEDEX_TRACKING_SOAP_SANDBOX_USER_KEY']
		FEDEX_TRACKING_SOAP_USER_PASSWORD = environ['FEDEX_TRACKING_SOAP_SANDBOX_USER_PASSWORD']
		FEDEX_TRACKING_SOAP_CLIENT_ACCOUNT = environ['FEDEX_TRACKING_SOAP_SANDBOX_CLIENT_ACCOUNT']
		FEDEX_TRACKING_SOAP_CLIENT_METER = environ['FEDEX_TRACKING_SOAP_SANDBOX_CLIENT_METER']
		FEDEX_TRACKING_SOAP_VERSION_MAJOR = environ['FEDEX_TRACKING_SOAP_SANDBOX_VERSION_MAJOR']
		FEDEX_TRACKING_SOAP_VERSION_MIDDLE = environ['FEDEX_TRACKING_SOAP_SANDBOX_VERSION_MIDDLE']
		FEDEX_TRACKING_SOAP_VERSION_MINOR = environ['FEDEX_TRACKING_SOAP_SANDBOX_VERSION_MINOR']
	else:
		FEDEX_URL = environ['FEDEX_SANDBOX_URL']
		FEDEX_TRACKING_API_KEY = environ['FEDEX_TRACKING_SANDBOX_API_KEY']
		FEDEX_TRACKING_SECRET_KEY = environ['FEDEX_TRACKING_SANDBOX_SECRET_KEY']
